spring:
  datasource:
    url: jdbc:mysql://10.234.126.86:3306/course_db
    username: course
    password: Pwd1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-test-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate   # 生产只校验
  # sql:
  #   init:
  #     mode: always
  #     data-locations: classpath:db/data.sql
